# Generated by Django 5.0.2 on 2024-02-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('address_number', models.CharField(max_length=15, verbose_name='Número')),
                ('address_city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=127, verbose_name='Estado')),
                ('address_postal_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('address_latitude', models.CharField(max_length=15, verbose_name='Latitude')),
                ('address_longitude', models.CharField(max_length=15, verbose_name='Longitude')),
                ('address_created_at', models.DateTimeField(verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_name', models.CharField(max_length=255, verbose_name='Disponibilidade/Validade')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitMeasurement_type', models.CharField(max_length=8, verbose_name='Tipo de Unidade de Medida')),
            ],
            options={
                'verbose_name': ('Unidade de Medida',),
                'verbose_name_plural': 'Unidade de Medida',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=45, verbose_name='Nome')),
                ('establishment_legal_name', models.CharField(max_length=45, verbose_name='Razão Social')),
                ('establishment_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('establishment_description', models.CharField(max_length=255, verbose_name='Descrição do Estabelecimento')),
                ('establishment_address_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.address', verbose_name='Endereço')),
                ('establishment_phone_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.phone', verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Produto')),
                ('product_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor')),
                ('product_code', models.CharField(max_length=255, verbose_name='Código')),
                ('product_available_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.available', verbose_name='Disponibilidade')),
                ('product_category_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.category', verbose_name='Categoria')),
                ('product_UnitMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.UnitMeasurement', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
