# Generated by Django 5.0.2 on 2024-02-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_value',
            new_name='product_price',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('order_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('order_is_paid', models.BooleanField(default=False, verbose_name='Pagamento')),
                ('order_establishment_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.establishment', verbose_name='Estabelecimento')),
                ('order_user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Consumidor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('order_item_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.order', verbose_name='Item')),
                ('order_item_product_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items_pk',
            field=models.ManyToManyField(through='establishment.OrderItem', to='establishment.product'),
        ),
    ]
